package com.imagination.technologies.ora.app.greendao;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CHAT_ROOM.
 */
public class ChatRoom {

    private Long id;
    private Integer kChatRoomId;
    private Integer kUserId;
    private String kChatRoomName;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ChatRoomDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ChatRoom() {
    }

    public ChatRoom(Long id) {
        this.id = id;
    }

    public ChatRoom(Long id, Integer kChatRoomId, Integer kUserId, String kChatRoomName) {
        this.id = id;
        this.kChatRoomId = kChatRoomId;
        this.kUserId = kUserId;
        this.kChatRoomName = kChatRoomName;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getChatRoomDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getKChatRoomId() {
        return kChatRoomId;
    }

    public void setKChatRoomId(Integer kChatRoomId) {
        this.kChatRoomId = kChatRoomId;
    }

    public Integer getKUserId() {
        return kUserId;
    }

    public void setKUserId(Integer kUserId) {
        this.kUserId = kUserId;
    }

    public String getKChatRoomName() {
        return kChatRoomName;
    }

    public void setKChatRoomName(String kChatRoomName) {
        this.kChatRoomName = kChatRoomName;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ChatRoom chatRoom = (ChatRoom) o;

        return !(kChatRoomId != null ? !kChatRoomId.equals(chatRoom.kChatRoomId) : chatRoom.kChatRoomId != null);

    }

    @Override
    public int hashCode() {
        return kChatRoomId != null ? kChatRoomId.hashCode() : 0;
    }
    // KEEP METHODS END

}
