package com.imagination.technologies.ora.app.greendao;

import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CHAT_MESSAGE.
 */
public class ChatMessage {

    private Long id;
    private Integer kChatId;
    private Integer kMessageId;
    private Integer kSenderId;
    private String kMessage;
    private String kUserName;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ChatMessageDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ChatMessage() {
    }

    public ChatMessage(Long id) {
        this.id = id;
    }

    public ChatMessage(Long id, Integer kChatId, Integer kMessageId, Integer kSenderId, String kMessage, String kUserName) {
        this.id = id;
        this.kChatId = kChatId;
        this.kMessageId = kMessageId;
        this.kSenderId = kSenderId;
        this.kMessage = kMessage;
        this.kUserName = kUserName;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getChatMessageDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getKChatId() {
        return kChatId;
    }

    public void setKChatId(Integer kChatId) {
        this.kChatId = kChatId;
    }

    public Integer getKMessageId() {
        return kMessageId;
    }

    public void setKMessageId(Integer kMessageId) {
        this.kMessageId = kMessageId;
    }

    public Integer getKSenderId() {
        return kSenderId;
    }

    public void setKSenderId(Integer kSenderId) {
        this.kSenderId = kSenderId;
    }

    public String getKMessage() {
        return kMessage;
    }

    public void setKMessage(String kMessage) {
        this.kMessage = kMessage;
    }

    public String getKUserName() {
        return kUserName;
    }

    public void setKUserName(String kUserName) {
        this.kUserName = kUserName;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ChatMessage that = (ChatMessage) o;

        return !(kMessageId != null ? !kMessageId.equals(that.kMessageId) : that.kMessageId != null);

    }

    @Override
    public int hashCode() {
        return kMessageId != null ? kMessageId.hashCode() : 0;
    }
    // KEEP METHODS END

}
