package com.imagination.technologies.ora.app.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * DAO for table CHAT_ROOM.
*/
public class ChatRoomDao extends AbstractDao<ChatRoom, Long> {

    public static final String TABLENAME = "CHAT_ROOM";

    /**
     * Properties of entity ChatRoom.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property KChatRoomId = new Property(1, Integer.class, "kChatRoomId", false, "K_CHAT_ROOM_ID");
        public final static Property KUserId = new Property(2, Integer.class, "kUserId", false, "K_USER_ID");
        public final static Property KChatRoomName = new Property(3, String.class, "kChatRoomName", false, "K_CHAT_ROOM_NAME");
    };

    private DaoSession daoSession;


    public ChatRoomDao(DaoConfig config) {
        super(config);
    }

    public ChatRoomDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CHAT_ROOM' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'K_CHAT_ROOM_ID' INTEGER," + // 1: kChatRoomId
                "'K_USER_ID' INTEGER," + // 2: kUserId
                "'K_CHAT_ROOM_NAME' TEXT);"); // 3: kChatRoomName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CHAT_ROOM'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ChatRoom entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Integer kChatRoomId = entity.getKChatRoomId();
        if (kChatRoomId != null) {
            stmt.bindLong(2, kChatRoomId);
        }

        Integer kUserId = entity.getKUserId();
        if (kUserId != null) {
            stmt.bindLong(3, kUserId);
        }

        String kChatRoomName = entity.getKChatRoomName();
        if (kChatRoomName != null) {
            stmt.bindString(4, kChatRoomName);
        }
    }

    @Override
    protected void attachEntity(ChatRoom entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /** @inheritdoc */
    @Override
    public ChatRoom readEntity(Cursor cursor, int offset) {
        ChatRoom entity = new ChatRoom( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // kChatRoomId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // kUserId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // kChatRoomName
        );
        return entity;
    }

    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ChatRoom entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKChatRoomId(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setKUserId(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setKChatRoomName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }

    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ChatRoom entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /** @inheritdoc */
    @Override
    public Long getKey(ChatRoom entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
